// packages/react/src/components/Ripple.tsx
import React, {
  cloneElement,
  FC,
  ReactElement,
  ReactNode,
  SyntheticEvent,
  useEffect,
} from "react";
import { useRipple } from "@material-yue/common";

interface RippleProps {
  // children: Array<ReactElement>;
}
export const Ripple: FC<RippleProps> = ({ children }, context) => {
  const reactNode: ReactNode = children;
  const { ripple, rippleOut } = useRipple();

  const onMouseDown = (event: SyntheticEvent) => {
    ripple({ event: event.nativeEvent, element: event.currentTarget });
  };
  const onMouseLeave = () => {
    rippleOut();
  };
  useEffect(() => {
    // reactNode.addEventListener()
  }, []);
  return (
    <>
      {cloneElement(reactNode, {
        onMouseDown,
        onMouseLeave,
        onMouseUp: onMouseLeave,
      })}
    </>
  );
};

// packages/material-yue/src/components/Ripple.vue
<template>
  <slot></slot>
</template>
<script lang="ts">
import { h } from "vue";
import { useRipple } from "@material-yue/common";

export default {
  name: "Ripple",
  setup(props, context){
    const { ripple, rippleOut } = useRipple();

    const onMousedown = (event) => {
      ripple({event: event, element: event.currentTarget})
    }
    const onMouseleave = () => {
      rippleOut();
    }
    const element = context.slots.default()[0];
    return () => h(element.type, {...element.props, onMousedown, onMouseup: onMouseleave, onMouseleave}, element.children)
  }
}
</script>
