// packages/react/src/components/Button.tsx
import React, { useContext } from "react";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";
import { useTheme } from "../hooks/useTheme";
import { Ripple } from "./Ripple";
interface ButtonProps {
  icon: any;
  children?: JSX.Element;
  className: string;
  disabled: boolean;
  onClick?: () => {};
}
export const Button = ({
  icon,
  disabled,
  children,
  className,
}: ButtonProps) => {
  const { ThemeContext, VariantContext } = useTheme();
  const tokens = useContext(ThemeContext);
  const variant: string = useContext(VariantContext);

  const theme = m3(tokens, { variant });

  const btn = css(
    applyReactiveStyle({
      target: m3(tokens, { variant }).components.Button,
      theme,
    })
  );
  return (
    <Ripple>
      <button className={`${btn} ${className}`}>
        <div className="state" />
        {icon}
        <div>{children}</div>
      </button>
    </Ripple>
  );
};

// packages/material-toys/src/components/_Button.vue
<template>
  <button ref="root" :class="btn"><slot></slot></button>
</template>
<script lang="ts">
import { computed, inject, onMounted, ref, watchEffect } from "vue";
import { css, cx } from "@emotion/css";
import { applyReactiveStyle } from "@material-toys/common";
import useClipPathData from "../composables/useClipPathData";
import useResizeEvents from "../composables/useResizeEvents";

export default {
  name: "Button",
  setup() {
    const theme: any = inject("theme");
    const root = ref(null);
    const style = ref(null);
    const width = ref(0);
    const height = ref(0);
    const btn = computed(() =>
      css(
        (style.value = applyReactiveStyle({
          target: theme.components.Button,
          theme,
          width,
          height,
        }))
      )
    );
    const resizingBtn = computed(() =>
      css(
        (style.value = [
          applyReactiveStyle({
            target: theme.components.Button,
            theme,
            width,
            height,
          }),
          setDynamic({
            target: theme.components._resizingComponent,
            theme,
            height,
            width,
          }),
        ])
      )
    );
    useClipPathData({ root, style });
    useResizeEvents({ root, cname: resizingBtn, width, height });
    return { resizingBtn, root, btn };
  },
};
</script>
