// packages/react/src/components/Card.tsx
import React, { ReactNode, useContext, useRef, useEffect } from "react";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";
import { useTheme } from "../hooks/useTheme";
import { Ripple } from "./Ripple";
interface CardProps {
  disabled: boolean;
  className: string;
  onClick?: Function;
  children?: ReactNode;
}
export const Card = ({ children, className }: CardProps) => {
  const { ThemeContext, VariantContext } = useTheme();
  const tokens = useContext(ThemeContext);
  const variant: string = useContext(VariantContext);
  const node = useRef(null);
  const theme = m3(tokens, { variant });
  let width, height;
  let card = css(
    applyReactiveStyle({
      target: "components.Card",
      theme,
      width,
      height,
    })
  );
  useEffect(() => {
    if (node?.current) {
      ({ width, height } = node.current.getBoundingClientRect());
      console.log("new width", width);
      card = css(
        applyReactiveStyle({
          target: "components.Card",
          theme,
          width,
          height,
        })
      );
      console.log("new classname", card);
      // should apply the new created class name
    }
  }, [node]);
  return (
    <Ripple>
      <div ref={node} className={`${card} ${className}`}>
        <div className="state" />
        {children}
      </div>
    </Ripple>
  );
};

// packages/material-toys/src/components/_Card.vue
<template>
  <div ref="root" :class="card"><slot></slot></div>
</template>
<script lang="ts">
import { computed, inject, onMounted, ref } from "vue";
import { css, cx } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";
import useClipPathData from "../composables/useClipPathData";
import useResizeEvents from "../composables/useResizeEvents";

export default {
  name: "Card",
  setup() {
    const tokens: any = inject("tokens");
    const theme = m3(tokens);
    // const theme: any = inject("theme");
    const root = ref(null);
    const style = ref(null);
    const width = ref(0);
    const height = ref(0);

    const card = computed(() =>
      css(
        (style.value = applyReactiveStyle({
          target: m3(tokens).components.Card,
          theme,
          width,
          height,
        }))
      )
    );
    const resizingCard = computed(() =>
      css(
        (style.value = [
          applyReactiveStyle({
            target: theme.components.Card,
            theme,
            width,
            height,
          }),
          setDynamic({
            target: theme.components._resizingComponent,
            theme,
            height,
            width,
          }),
        ])
      )
    );

    useClipPathData({ root, style });
    useResizeEvents({ root, cname: resizingCard, width, height });

    return { card, root };
  },
};
</script>
