// packages/react/src/components/Card.tsx
import React, { ReactNode, useContext } from "react";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";
import { useTheme } from "../hooks/useTheme";
import { Ripple } from "./Ripple";
interface CardProps {
  disabled: boolean;
  className: string;
  onClick?: Function;
  children: ReactNode;
}
export const Card = ({ children, className }: CardProps) => {
  const { ThemeContext, VariantContext } = useTheme();
  const tokens = useContext(ThemeContext);
  const variant: string = useContext(VariantContext);

  const theme = m3(tokens, { variant });

  const card = css(
    applyReactiveStyle({
      target: m3(tokens, { variant }).components.Card,
      theme,
    })
  );
  return (
    <Ripple>
      <div className={`${card} ${className}`}>
        <div className="state" />
        {children}
      </div>
    </Ripple>
  );
};

// packages/material-toys/src/components/Card.vue
<script lang="ts">
import { computed, inject, Ref, ref } from "vue";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";

export default {
  name: "Card",
  setup() {
    const tokens: any = inject("tokens");
    const variant: any = inject("variant");
    const theme = m3(tokens, { variant: variant.value });
    const root = ref(null);
    const style = ref(null);
    const width = ref(0);
    const height = ref(0);
    const card = computed(() =>
      css(
        (style.value = applyReactiveStyle({
          target: m3(tokens, { variant: variant.value }).components.Card,
          theme,
          width,
          height,
        }))
      )
    );
    return { root, card };
  },
};
</script>
<template>
  <div ref="root" :class="card">
    <div class="state"></div>
    <slot></slot>
  </div>
</template>
