// packages/react/src/components/Ripple.tsx
import React, {
  cloneElement,
  Context,
  ReactElement,
  ReactNode,
  SyntheticEvent,
  useEffect,
} from "react";
import { useRipple } from "@material-toys/common";

interface RippleProps {
  children: ReactNode;
}
export const Ripple = (
  { children }: RippleProps,
  context: Context<any>
): JSX.Element => {
  const reactNode: ReactNode = children;
  const { ripple, rippleOut } = useRipple();

  const onPointerDown = (event: SyntheticEvent) => {
    ripple({
      event: event.nativeEvent as PointerEvent,
      element: event.currentTarget as HTMLElement,
    });
  };
  const onPointerLeave = () => {
    rippleOut();
  };
  useEffect(() => {
    // reactNode.addEventListener()
  }, []);
  return (
    <>
      {cloneElement(reactNode as ReactElement<any>, {
        onPointerDown,
        onPointerLeave,
        onPointerUp: onPointerLeave,
      })}
    </>
  );
};

// packages/material-toys/src/components/Ripple.vue
<script lang="ts">
import { h } from "vue";
import { useRipple } from "@material-toys/common";

export default {
  name: "Ripple",
  setup(props, context) {
    const { ripple, rippleOut } = useRipple();

    const onPointerdown = (event) => {
      ripple({ event: event, element: event.currentTarget });
    };
    const onPointerleave = () => {
      rippleOut();
    };
    const element = context.slots.default()[0];
    // return () => h(element.type, {...element.props, onMousedown, onMouseup: onMouseleave, onMouseleave}, element.children)
    return () =>
      h(
        element.type,
        {
          ...context.slots.default()[0].props,
          onPointerdown,
          onPointerup: onPointerleave,
          onPointerleave,
        },
        context.slots.default()[0].children
      );
  },
};
</script>
