// packages/material-yue/src/components/Button.vue
<template>
  <Ripple>
  <button v-bind="$attrs" :class="btn">
    <div class="state">
    </div>
    <slot name="icon"></slot>
    <div><slot></slot></div></button>
  </Ripple>
</template>
<script lang="ts">
import { computed, inject, Ref, ref } from "vue";
import { css } from "@emotion/css";
import { setDynamic, m3 } from "@material-yue/common";
import Ripple from "./Ripple";

export default {
  inheritAttrs: false,
  name: "Button",
  components: {Ripple},
  setup(){
    const tokens: any = inject("tokens");
    const variant: any = inject("variant");
    const theme = m3(tokens, {variant:variant.value});
    const btn = computed(() => css(
        setDynamic({target: m3(tokens, {variant:variant.value}).components.Button, theme}),
    ));
    return { btn };
  }
}
</script>

// packages/react/src/components/Button.tsx
import React, { useContext } from "react";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-yue/common";
import { useTheme } from "../hooks/useTheme";
import { Ripple } from "./Ripple";
interface ButtonProps {
  icon: any;
  children?: JSX.Element;
  className: string;
  disabled: boolean;
  onClick?: Function;
}
export const Button = ({
  icon,
  disabled,
  children,
  className,
}: ButtonProps): JSX.Element => {
  const { ThemeContext, VariantContext } = useTheme();
  const tokens = useContext(ThemeContext);
  const variant = useContext(VariantContext);

  const theme = m3(tokens, { variant });

  const btn = css(
    applyReactiveStyle({
      target: m3(tokens, { variant }).components.Button,
      theme,
    })
  );
  return (
    <Ripple>
      <button className={`${btn} ${className}`}>
        <div className="state" />
        {icon}
        <div>{children}</div>
      </button>
    </Ripple>
  );
};
