// packages/material-toys/src/components/Button.vue
<script lang="ts">
import { computed, inject, Ref } from "vue";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";
import Ripple from "./Ripple.vue";

export default {
  inheritAttrs: false,
  name: "Button",
  components: { Ripple },
  setup() {
    const tokens: any = inject("tokens");
    const variant: Ref<string> = inject("variant");
    const theme = m3(tokens, { variant: variant.value });
    const btn = computed(() => {
      return css(
        applyReactiveStyle({
          target: m3(tokens, { variant: variant.value }).components.Button,
          theme,
        })
      );
    });
    // console.log("btn is", btn);
    // const btn = "btn";
    return { btn };
  },
};
</script>
<template>
  <Ripple>
    <button v-bind="$attrs" :class="btn">
      <div class="state"></div>
      <slot name="icon"></slot>
      <div><slot></slot></div>
    </button>
  </Ripple>
</template>

// packages/react/src/components/Button.tsx
import React, { useContext } from "react";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";
import { useTheme } from "../hooks/useTheme";
import { Ripple } from "./Ripple";
interface ButtonProps {
  icon: any;
  children?: JSX.Element;
  className: string;
  disabled: boolean;
  onClick?: () => {};
}
export const Button = ({
  icon,
  disabled,
  children,
  className,
}: ButtonProps) => {
  const { ThemeContext, VariantContext } = useTheme();
  const tokens = useContext(ThemeContext);
  const variant: string = useContext(VariantContext);

  const theme = m3(tokens, { variant });

  const btn = css(
    applyReactiveStyle({
      target: m3(tokens, { variant }).components.Button,
      theme,
    })
  );
  return (
    <Ripple>
      <button className={`${btn} ${className}`}>
        <div className="state" />
        {icon}
        <div>{children}</div>
      </button>
    </Ripple>
  );
};
