// packages/material-toys/src/components/ExtendedFAB.vue
<script lang="ts">
import { computed, inject, ref } from "vue";
import { css, cx } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";
import Ripple from "./Ripple";

export default {
  name: "ExtendedFAB",
  components: { Ripple },
  setup() {
    const tokens: any = inject("tokens");
    const variant: any = inject("variant");
    const theme = m3(tokens, { variant: variant.value });
    const efab = computed(() =>
      css(
        applyReactiveStyle({
          target: m3(tokens, { variant: variant.value }).components.ExtendedFAB,
          theme,
        })
      )
    );
    return { efab };
  },
};
</script>
<template>
  <Ripple>
    <button v-bind="$attrs" ref="root" :class="efab">
      <div class="state"></div>
      <slot name="icon"></slot>
      <div><slot></slot></div></button
  ></Ripple>
</template>

// packages/react/src/components/ExtendedFAB.tsx
import React, { FC, ReactNode, useContext } from "react";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-toys/common";
import { useTheme } from "../hooks/useTheme";
import { Ripple } from "./Ripple";
interface FABProps {
  children: ReactNode;
  disabled: boolean;
  className: string;
  onClick?: Function;
}
export const ExtendedFAB = ({ children, disabled, className }: FABProps) => {
  const { ThemeContext, VariantContext } = useTheme();
  const tokens = useContext(ThemeContext);
  const variant: string = useContext(VariantContext);

  const theme = m3(tokens, { variant });

  const efab = css(
    applyReactiveStyle({
      target: m3(tokens, { variant }).components.ExtendedFAB,
      theme,
    })
  );
  return (
    <Ripple>
      <button disabled={disabled} className={`${efab} ${className}`}>
        <div className="state" />
        {children}
      </button>
    </Ripple>
  );
};
