// packages/material-yue/src/components/FAB.vue
<template>
  <Ripple>
  <button v-bind="$attrs" ref="root" :class="fab">
    <div class="state">
    </div><slot></slot></button></Ripple>
</template>
<script lang="ts">
import { computed, inject, ref } from "vue";
import {css, cx} from "@emotion/css";
import {setDynamic, m3} from "@material-yue/common";
import Ripple from "./Ripple";

export default {
  name: "FAB",
  components: {Ripple},
  setup(){
    const tokens: any = inject("tokens");
    const variant: any = inject("variant");
    const theme = m3(tokens, {variant: variant.value});
    const root = ref(null);
    const style = ref(null);
    const width = ref(0);
    const height = ref(0);
    const fab = computed(() => css(
        style.value = setDynamic({target: m3(tokens, {variant: variant.value}).components.FAB, theme, width, height}),
    ));
    return { root, fab };
  }
}
</script>

// packages/react/src/components/FAB.tsx
import React, { ReactNode, useContext } from "react";
import { css } from "@emotion/css";
import { applyReactiveStyle, m3 } from "@material-yue/common";
import { useTheme } from "../hooks/useTheme";
import { Ripple } from "./Ripple";
interface FABProps {
  disabled: boolean;
  className: string;
  children: ReactNode;
  onClick?: () => {};
}
export const FAB = ({ children, disabled, className }: FABProps) => {
  const { ThemeContext, VariantContext } = useTheme();
  const tokens = useContext(ThemeContext);
  const variant: string = useContext(VariantContext);

  const theme = m3(tokens, { variant });

  const fab = css(
    applyReactiveStyle({
      target: m3(tokens, { variant }).components.FAB,
      theme,
    })
  );
  return (
    <Ripple>
      <button disabled={disabled} className={`${fab} ${className}`}>
        <div className="state" />
        {children}
      </button>
    </Ripple>
  );
};
